### ISSUE TITLE
Issue with "-" delimiter

### ISSUE THREAD

**Issue by risserlin** [BaderLab/WordCloudPlugin#47]
the "-" delimiter is not in the default set of delimiters. (when I run wordcloud there are a lot of hyphenated words that come up in the wordclouds)
When I add the "-" to the delimiters it gets added to the default delimiters and not to the user defined delimiters. (other delimiters that I add get added to user-defined list).

Not sure what is happening here.

**Comment by mikekucera** [comment]
There are actually three sets of delimiters:
default set of active delimiters
default set of inactive delimiters (shown in combo box under input field)
user defined delimiters

If you remove one of the default active delimiters it moves to the set of inactive delimiters. I think its because entering "tab" or "newline" is non-obvious, so they can be selected from the combo box. 

The UI doesn't make any of this obvious, so I will think about how to fix it. I will also move "-" to the default set of active delimiters.
